### ISSUE TITLE
After copying the files and starting the camera...

### ISSUE THREAD

**Issue by nc1618** [edsub/Goke_GK7102#1]
Is it expected that the hacks will run as soon as the camera starts? or do I need to run the files via a telnet session? sorry I am quite a noob. I have the DG MYQ with the same firmware.

Forgot to mention, great job, really appreciate the work that you have put on this. I had a look at the original post and around all the issues but could not find anything that could answer my question

**Comment by maps2002** [comment]
Hi,

The hacks should run as the camera starts.
At the end you can telnet to see if it was executed (look at the /home directory for a hack folder).

I had some problems applying this, but eventually was able:
 - The camera would not mount my sd card. Something to do with the way windows was formatting it vs the camera supported formats
 - At least the persistenthack.sh file was formatted with line endings with CRLF. Had to change them to just LF, or else the script would be badly executed

Seems to be working ok, so thank you to the author of this!
Are you planning any evolutions?

**Comment by nc1618** [comment]
Thanks a lot, I figured out the issue with the SD card formatting so did it on a Linux machine as vfat but I wouldn't have guessed the issue with the line endings, it works like a charm, thank you very much, and thanks again to the author, someone had the same issues on the original repository so will refer them to your answer.
